---
title: "Publications"
---

## Research Interests

- Item response theory, measurement, psychometrics
- Causal inference, program evaluation, policy
- Statistical methodology, computing, simulation
- Research synthesis, meta-analysis, meta-science

## Google Scholar Metrics

{{< include generated/scholar-stats.md >}}

## Publications

Notational conventions:

- `†`: Student collaborators with whom I engaged extensively during the project.
- `‡`: Paper on which I acted as a senior or corresponding author.
- `*`: Joint authorship.
- `...`: Lengthy authorship list (names omitted).
- `[...]`: Links to the article, replication materials, and media coverage, where applicable.

### Peer-Reviewed Journal Publications

#### Sole or First Author

- **Gilbert, J. B.**, Young, W. S., Himmelsbach, Z., Ulitzsch, E., and Domingue, B. W. (2026). Conditional dependencies between response time and item discrimination: An item-level meta-analysis. *Educational and Psychological Measurement*. [doi](https://doi.org/10.1177/00131644261426972), [code](https://doi.org/10.7910/DVN/OZUZ47)
- **Gilbert, J. B.** (2026). Explanatory item response models for continuous data: A tutorial in R. *Behavior Research Methods, 58*, 124. [doi](https://doi.org/10.3758/s13428-026-02986-2), [code](https://doi.org/10.7910/DVN/CIRSL1)
- **Gilbert, J. B.**, Domingue, B. W., and Kim, J. S. (2026). Estimating causal effects on psychological networks using item response theory. *Psychological Methods, 31*(1), 110-135. [doi](https://doi.org/10.1037/met0000764), [code](https://doi.org/10.7910/DVN/CVO9EZ)
- **Gilbert, J. B.**, Soland, J. G., and Domingue, B. W. (2026). The sensitivity of value-added estimates to test scoring decisions. *Educational Measurement: Issues and Practice, 45*(1). [doi](http://dx.doi.org/10.1111/emip.70011), [code](https://doi.org/10.7910/DVN/AJDUN2), [policy brief](https://scholars.org/contribution/how-test-scoring-decisions-affect-school)
- **Gilbert, J. B.**, and Miratrix, L. W. (2026). Multilevel metamodels: Enhancing inference, interpretability, and generalizability in Monte Carlo simulation studies. *Multivariate Behavioral Research, 61*(2), 287-310. [doi](https://doi.org/10.1080/00273171.2025.2586631), [code](https://researchbox.org/2429)
- **Gilbert, J. B.**, Himmelsbach, Z., Miratrix, L. W., Ho, A. D., and Domingue, B. W. (2025). Item-level heterogeneity in value added models: Implications for reliability, cross-study comparability, and effect sizes. *Journal of Educational and Behavioral Statistics*. [doi](https://journals.sagepub.com/doi/10.3102/10769986251393339), [code](https://doi.org/10.7910/DVN/89YITQ)
- **Gilbert, J. B.**, Himmelsbach, Z., Soland, J., Joshi, M., and Domingue, B. W. (2025). Estimating heterogeneous treatment effects with item-level outcome data: Insights from item response theory. *Journal of Policy Analysis and Management, 44*(4), 1417-1449. [doi](https://doi.org/10.1002/pam.70025), [code](https://doi.org/10.7910/DVN/C4TJCA)
- **Gilbert, J. B.** (2025). Estimating treatment effects with the explanatory item response model. *Journal of Research on Educational Effectiveness, 18*(1), 166-184. [doi](https://www.tandfonline.com/doi/pdf/10.1080/19345747.2023.2287601), [code](https://researchbox.org/797)
- **Gilbert, J. B.** (2025). How measurement affects causal inference: Attenuation bias is (usually) more important than outcome scoring weights. *Methodology, 21*(2), 91-122. [doi](https://doi.org/10.5964/meth.15773), [code](https://researchbox.org/2289)
- **Gilbert, J. B.**, Zhang, L., Ulitzsch, E., and Domingue, B. W. (2025). Polytomous explanatory item response models for item discrimination: Assessing negative-framing effects in social-emotional learning surveys. *Behavior Research Methods, 57*, 109. [doi](https://doi.org/10.3758/s13428-025-02625-2), [code](https://researchbox.org/3008)
- **Gilbert, J. B.**, Miratrix, L. W., Joshi, M., and Domingue, B. W. (2025). Disentangling person-dependent and item-dependent causal effects: Applications of item response theory to the estimation of treatment effect heterogeneity. *Journal of Educational and Behavioral Statistics, 50*(1), 72-101. [doi](https://doi.org/10.3102/10769986241240085), [code](https://researchbox.org/2221)
- **Gilbert, J. B.**, Kim, J. S., and Miratrix, L. W. (2024). Leveraging item parameter drift to assess transfer effects in vocabulary learning. *Applied Measurement in Education, 37*(3), 240-257. [doi](https://doi.org/10.1080/08957347.2024.2386934), [code](https://doi.org/10.7910/DVN/ZF1LKZ)
- **Gilbert, J. B.**, Hieronymus, F., Eriksson, E., and Domingue, B. W. (2024). Item-level heterogeneous treatment effects of Selective Serotonin Reuptake Inhibitors (SSRIs) on depression: Implications for inference, generalizability, and identification. *Epidemiologic Methods, 13*(S2), 20240006, 1-17. [doi](https://doi.org/10.1515/em-2024-0006), [code](https://researchbox.org/2494)
- **Gilbert, J. B.** (2024). Modeling item-level heterogeneous treatment effects: A tutorial with the `glmer` function from the `lme4` package in R. *Behavior Research Methods, 56*(5), 5055-5067. [doi](https://link.springer.com/article/10.3758/s13428-023-02245-8), [code](https://researchbox.org/2054)
- **Gilbert, J. B.**, Kim, J. S., and Miratrix, L. W. (2023). Modeling item-level heterogeneous treatment effects with the explanatory item response model: Leveraging large-scale online assessments to pinpoint the impact of educational interventions. *Journal of Educational and Behavioral Statistics, 48*(6), 889-913. [doi](https://journals.sagepub.com/doi/pdf/10.3102/10769986231171710), [code](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QARRYT)

#### Co-authored (Education/Quantitative Methods)

- Nalbandyan, R., **Gilbert, J. B.**, Franco, V. R., and Domingue, B. W. (2026). Signposts on the path from nominal to ordinal scales: Moving from a discrete to a continuous view. *Educational and Psychological Measurement*. [doi](https://journals.sagepub.com/doi/10.1177/00131644261440556), [code](https://github.com/rn2407stanford/Category_Order)
- Domingue, B. W., Braginsky, M., Caffrey-Maffei, L. A., **Gilbert, J. B.** ... and Frank, M. C. (2025). An introduction to the Item Response Warehouse (IRW): A resource for enhancing data usage in psychometrics. *Behavior Research Methods, 57*, 276. [doi](https://doi.org/10.3758/s13428-025-02796-y)
- Relyea, J. E., **Gilbert, J. B.**, ... and Kim, J. S. (2025). Asset-based implementation of structured adaptations in an online third-grade content literacy intervention. *Reading Research Quarterly, 60*(4). [doi](https://doi.org/10.1002/rrq.70048), [code](https://doi.org/10.7910/DVN/JDUIKT), [EWP Policy and Practice](https://edworkingpapers.com/policy-practice-series/ai24-1001)
- Kim, J. S., **Gilbert, J. B.**, ... and Tvedt, J. N. (2024). Time to transfer: Long-term effects of a sustained and spiraled content literacy intervention in the elementary grades. *Developmental Psychology, 60*(7), 1279-1297. [doi](https://doi.org/10.1037/dev0001710), [code](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RKBVKY), [Harvard Ed. Magazine](https://www.gse.harvard.edu/ideas/ed-magazine/24/05/phase-two-reach), [NBC News](https://www.nbcnews.com/now/video/new-program-tackles-literacy-challenges-in-classrooms-212046405968), [Hechinger Report](https://hechingerreport.org/proof-points-learning-science-might-help-kids-read-better/), [MetaMetrics](https://metametricsinc.com/neenas-top-reading-research-picks-for-april-2024/), [American Educator](https://www.aft.org/ae/winter2024-2025/catts_kamhi), [Minding the Gap](https://nataliewexler.substack.com/p/beyond-reading-comprehension-strategies?utm_source=post-email-title&publication_id=443300&post_id=149031506&utm_campaign=email-post-title&isFreemail=true&r=1nz8v7&triedRedirect=true&utm_medium=email), [Harvard Magazine](https://www.harvardmagazine.com/2024/09/harvard-reading-wars-literacy-education)
- Relyea, J. E., Rich, P., Kim, J. S., and **Gilbert, J. B.** (2023). The COVID-19 impact on reading achievement growth of Grade 3-5 students in a US urban school district: variation across student characteristics and instructional modalities. *Reading and Writing, 36*(2), 317-346. [doi](https://link.springer.com/article/10.1007/s11145-022-10387-y), [Science Daily](https://www.sciencedaily.com/releases/2022/11/221117102858.htm)
- Kim, J. S., Burkhauser, M. A., Relyea, J. E., **Gilbert, J. B.**, ... and McIntyre, J. (2023). A longitudinal randomized trial of a sustained content literacy intervention from first to second grade: Transfer effects on students' reading comprehension. *Journal of Educational Psychology, 115*(1), 73-96. [doi](https://psycnet.apa.org/record/2022-69392-001), [code](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LAWFFU), [supplement](https://supp.apa.org/psycarticles/supplemental/edu0000751/edu0000751_supp.html), [Forbes](https://www.forbes.com/sites/nataliewexler/2023/02/22/new-study-suggests-standardized-reading-tests-miss-a-lot-of-learning/?sh=261d3314a46b), [Education Week](https://www.edweek.org/teaching-learning/what-is-background-knowledge-and-how-does-it-fit-into-the-science-of-reading/2023/01)
- Kim, J., **Gilbert, J.**, Yu, Q., and Gale, C. (2021). Measures matter: A meta-analysis of the effects of educational apps on preschool to grade 3 children's literacy and math skills. *AERA Open, 7*, 23328584211004183. [doi](https://journals.sagepub.com/doi/pdf/10.1177/23328584211004183), [code](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/V17T2Y), [New York Times](https://www.nytimes.com/2024/04/17/opinion/educational-technology.html)
- Scripp, L., and **Gilbert, J.** (2016). Music plus music integration: A model for music education policy reform that reflects the evolution and success of arts integration practices in 21st century American public schools. *Arts Education Policy Review, 117*(4), 186-202. [doi](https://www.tandfonline.com/doi/pdf/10.1080/10632913.2016.1211923)

#### Co-authored (Health Science/Biostatistics)

- Ashourizadeh, A.\*, **Gilbert, J. B.**\* ... and Armstrong, G. W. (2026). Impact of cataract surgery on the risk of conversion from dry to neovascular age-related macular degeneration in the IRIS Registry. *Ophthalmology*. [doi](https://www.aaojournal.org/article/S0161-6420(26)00420-3/abstract)
- Berkowitz, S. T., **Gilbert, J. B.**, ... and Finn, A. P. (2026). Characterization of intravitreal anti-VEGF injection transitions across bevacizumab, biosimilar, and branded medications: IRIS (Intelligent Research in Sight) Registry study. *Journal of VitreoRetinal Diseases*. [doi](https://doi.org/10.1177/24741264261455206)
- Armstrong-Carter, E., **Gilbert, J. B.**, Silfverskiold, T., Clark, L. E., and Templin, T. (2026). Adolescents provide approximately \$15 billion worth of informal family caregiving services to the United States economy. *Children and Youth Services Review, 188*. [doi](https://doi.org/10.1016/j.childyouth.2026.109121), [code](https://researchbox.org/2759)
- Ghauri, S., Ross, C., **Gilbert, J. B.** ... and Krzystolik, M. G. (2026). Timing and determinants of post-injection endophthalmitis after first-time anti-VEGF administration: A retrospective national study in the American Academy of Ophthalmology IRIS Registry. *Ophthalmology Retina*. [doi](https://doi.org/10.1016/j.oret.2026.03.015)
- Hoyek, S., **Gilbert, J. B.** ... and Patel, N. A. (2026). Intraocular pressure changes following vitrectomy with and without phacoemulsification: An IRIS Registry analysis. *Canadian Journal of Ophthalmology, 61*(2), 300-308. [doi](https://doi.org/10.1016/j.jcjo.2025.08.008)
- Nestorova, T., Nestorov, I., **Gilbert, J. B.**, and Howell, I. (2025). Does vibrato define genre or vice versa? A novel parametric approach to vibrato analysis. *Journal of Voice*. [doi](https://doi.org/10.1016/j.jvoice.2025.02.046)
- Tainsh, L., Douglas, V. P., **Gilbert, J. B.** ... and Lorch, A. (2025). Patient and practice level visual acuity prior to cataract surgery: An IRIS Registry (Intelligent Research in Sight) analysis. *Clinical Ophthalmology, 19*, 4975-4987. [doi](https://www.dovepress.com/articles.php?article_id=110610)
- Vu, D. M., **Gilbert, J. B.**, ... and Miller, J. W. (2025). Factors associated with gonioscopy coding before glaucoma procedures in the IRIS Registry. *American Journal of Ophthalmology, 279*, 253-263. [doi](https://doi.org/10.1016/j.ajo.2025.08.001)
- Zidan, A. A., **Gilbert, J. B.**, ... and Yin, J. (2025). Neurotrophic keratopathy in pediatric population: An IRIS Registry report. *Ophthalmology, 132*(9), 1063-1066. [doi](https://doi.org/10.1016/j.ophtha.2025.04.020)
- Ross, C., Ghauri, S., **Gilbert, J. B.** ... and Krzystolik, M. G. (2025). Intravitreal antibiotics versus early vitrectomy plus intravitreal antibiotics for post-injection endophthalmitis: An IRIS registry (Intelligent Research in Sight) analysis. *Ophthalmology Retina, 9*(3), 224-231. [doi](https://doi.org/10.1016/j.oret.2024.09.002)
- Zidan, A. A., **Gilbert, J. B.** ... and Yin, J. (2025). Nerve growth factor treatment for neurotrophic keratopathy in the IRIS registry. *Ophthalmology, 132*(3), 368-370. [doi](https://doi.org/10.1016/j.ophtha.2024.10.036)
- Ha, S. K.\*, **Gilbert, J. B.**\*, Le, E., Ross, C., and Lorch, A. (2025). Impact of teleretinal screening program on diabetic retinopathy screening compliance rates in community health centers: a quasi-experimental study. *BMC Health Services Research, 25*, 318. [doi](https://doi.org/10.1186/s12913-025-12472-8), [code](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/T5HXUE)

### Conference Papers

- Student, S. R., **Gilbert, J. B.**, Eze, J., Young, W. S., and Domingue, B. W. (2026). Item-level heterogeneous treatment effects in instrumental variables regression. *Proceedings of the International Meeting of the Psychometric Society*. [doi](https://doi.org/10.64028/imps2025.3NE3nHCRtP)
- Isley, C., **Gilbert, J. B.** ... and Goel, S. (2026). Assessing the quality of AI-generated exams: A large-scale field study. *Proceedings of the AAAI Conference on Artificial Intelligence, 40*(45), 38626-38634. [doi](https://ojs.aaai.org/index.php/AAAI/article/view/41205)
- Kakarla, S.†, Yanney, L.†, **Gilbert, J. B.**‡, and Domingue, B. W.‡ (2025). Exploring item-level heterogeneous treatment effects in educational interventions through machine learning techniques and item response models. 2024 IEEE MIT Undergraduate Research Technology Conference (URTC), Cambridge, MA, USA. [doi](https://ieeexplore.ieee.org/document/10937510)

### Book Chapters

- Scripp, L., and **Gilbert, J.** (2019). Human development through music. In L. Scripp and B. Kaufman (Eds.), *Music learning as youth development* (pp. 8-39). Routledge. [link](https://www.routledge.com/Music-Learning-as-Youth-Development/Kaufman-Scripp/p/book/9781138347700)

### Working Papers

#### Manuscripts in Revision

- Soland, J., and **Gilbert, J. B.** (2026). Does socially desirable responding increase after an intervention? Implications for estimating treatment effects. Under revision in *Journal of Experimental Education*. [doi](https://doi.org/10.31234/osf.io/ujx4n_v3)
- Veltri, G. A.\*, and **Gilbert, J. B.**\* (2026). Results from randomized controlled trials are highly sensitive to data preprocessing decisions: A multiverse analysis of 97 outcomes. Under revision in *Advances in Methods and Practice in Psychological Science*. [doi](https://doi.org/10.31222/osf.io/kbgc2_v2)
- **Gilbert, J. B.** and Kim, J. S. (2026). Mapping the mechanisms of interdisciplinary learning transfer from reading to math achievement: Evidence from a large-scale randomized controlled trial. Under revision in *Developmental Psychology*. [doi](https://edworkingpapers.com/ai26-1376), [The Bell Ringer](https://hollykorbey.substack.com/p/public-notice-4?utm_source=post-email-title&publication_id=235252&post_id=191361947&utm_campaign=email-post-title&isFreemail=false&r=44ycu&triedRedirect=true&utm_medium=email)
- Burkhauser, M. A., Kim, J. S., Mosher, D., Scherer, E., **Gilbert, J. B.**, Tvedt, J., and Grob, L. (2026). Empower the few to reach the many: An implementation strategy to support adoption, spread, and reform ownership of a first-grade content literacy program. Under revision in *Scientific Studies of Reading*.
- **Gilbert, J. B.** and Soland, J. (2024). Mechanisms of effect size differences between researcher developed and independently developed outcomes: An item-level meta-analysis. Under revision in *Multivariate Behavioral Research*. [doi](https://edworkingpapers.com/ai24-1082)
- Halpin, P. F., and **Gilbert, J. B.** (2024). Testing whether reported treatment effects are unduly influenced by item-level heterogeneity. Under revision in *Journal of Research on Educational Effectiveness*. [doi](https://osf.io/preprints/psyarxiv/9ru45_v1)

#### Manuscripts Under Review

- Ashourizadeh, A.\*, **Gilbert, J. B.**\* ... and Armstrong, G. W. (2026). Visual outcomes of cataract surgery in patients with age-related macular degeneration. Under review in *Journal of Cataract & Refractive Surgery*.
- **Gilbert, J. B.**, Kim, E. J., Himmelsbach, Z., Ulitzsch, E., and Zhang, L. (2026). Idiographic item response theory: Modeling person-specific differential item functioning in intensive longitudinal data. Under review in *Multivariate Behavioral Research*. [doi](https://osf.io/preprints/psyarxiv/qfcbu_v1)
- Whitcomb, N., **Gilbert, J. B.**, Ross, C., Kearney, W., Lorch, A., and Lee, H. J. (2026). Comparative surgical outcomes and predictors of surgical intervention in recurrent corneal erosion: An IRIS Registry study. Under review in *Cornea*.
- **Gilbert, J. B.**\*, Soland, J. G.\*, and Young, W. S. (2026). Is the replication crisis a measurement crisis? Evidence from over 100 randomized trial outcomes. Under review in *Nature*. [doi](https://osf.io/preprints/psyarxiv/9zgj8_v1)
- Cho, S-J., and **Gilbert, J. B.** (2026). Explanatory item response models with random item parameters and their applications. (Book Chapter)
- Dahrouj, M., Awh, C., Bleicher, I. D., **Gilbert, J. B.** ... and Singh, R. P. (2026). Preoperative vision as a predictor of surgical outcomes for idiopathic epiretinal membranes: an IRIS Registry study. Under review in *Ophthalmology*.
- **Gilbert, J. B.** and Himmelsbach, Z. (2026). Why fadeout is (probably) worse than we think: Adjusting for correlated sampling error in meta-analyses of behavioral interventions. Under review in *Psychological Methods*. [doi](https://edworkingpapers.com/ai26-1394)
- Gilson, A. Vonsachang, H., **Gilbert, J. B.** ... and Lindsay, J. L. (2025). Rates of laser peripheral iridotomy vs. lens extraction in the treatment of angle closure glaucoma: an IRIS registry (Intelligent Research in Sight) analysis. Under review in *Ophthalmology*.
- Zhang, L., Liu, Y., Molenaar, D., **Gilbert, J. B.**, Kanopka, K., and Domingue, B. W. (2025). Realistic simulation of item difficulties. Under review in *Behavior Research Methods*. [doi](https://osf.io/preprints/psyarxiv/jbhxy_v4)

#### Manuscripts in Preparation

- Himmelsbach, Z., and **Gilbert, J. B.** (2026). When randomization identifies partial adoption: Odd-sized sites as a diagnostic for policy-estimand mismatch.
- Hardy, M., **Gilbert, J. B.**, and Domingue, B. (2026). Efficient detection of bad benchmark items with novel scalability coefficients. [doi](https://arxiv.org/abs/2603.24999)
- Student, S. R., Eze, J., **Gilbert, J. B.**, Young, W. S., and Domingue, B. W. (2025). Expanding psychology's causal toolkit: Latent outcomes and binary treatments in instrumental variables regression.
- Himmelsbach, Z., and **Gilbert, J. B.** (2025). The case for Bayesian estimation of the D-study.

### Popular Press

- **Gilbert, J.**, and Kim, J. (2023). Do Educational Apps Actually Help Kids Learn? *Education Week*. [link](https://www.edweek.org/technology/opinion-do-educational-apps-actually-help-kids-learn/2023/10)
- Scripp, L., and **Gilbert, J.** (2016). All that Matters is How Good it Sounds. *VAN Magazine*. [link](https://van-magazine.com/mag/all-that-matters/)
