---
title: "Service"
---

## Editorial Positions

- Editorial Board, Applied Measurement in Education (2026-present)

## University Service

- Convener, HGSE Measurement Lab (2025-2026), Harvard GSE
- Faculty Search, Applied Quantitative Methods for Educational Research (2024), Harvard GSE
- Member, Faculty Council (2021-2022), New England Conservatory

## Professional Organizations

- Standards and Test Use Committee (Member) (2026-2029), National Council on Measurement in Education (NCME) ([link](https://www.ncme.org/community/ncme-committees/standard-test-use))
- Standards and Test Use Committee (Student representative) (2024-2026), National Council on Measurement in Education (NCME) ([link](https://www.ncme.org/community/ncme-committees/standard-test-use))

## Ad Hoc Review

Parentheses indicate multiple reviews at a journal.

### Journals

- Journal of Research on Educational Effectiveness (4)
- Journal of Educational Measurement (3)
- Journal of Educational and Behavioral Statistics (2)
- British Journal of Mathematical and Statistical Psychology (2)
- BMC Psychology (2)
- Methods in Psychology (2)
- Psychometrika (2)
- Applied Measurement in Education (2)
- AERA Open
- Psychological Methods
- American Psychologist
- Advances in Methods and Practices in Psychological Science
- Behavior Research Methods
- Review of Educational Research
- Mind, Brain, and Education
- BMC Medical Research Methodology

### Conference Proposals

- Society for Research on Educational Effectiveness

### Other Review Work

- NCES Psychometric Standards

## Other

- Data contributor, Item Response Warehouse (IRW) ([link](https://itemresponsewarehouse.org))

## Professional Affiliations

- Scholars Strategy Network (SSN) ([link](https://scholars.org/scholar/joshua-baer-gilbert))
- American Educational Research Association (AERA)
- National Council on Measurement in Education (NCME)
- Psychometric Society
- Society for Research on Educational Effectiveness (SREE)
- Institute for Quantitative Social Science (IQSS) Graduate Student Affiliate (2024-2026) ([link](https://www.iq.harvard.edu/people/joshua-gilbert))
