---
title: "Teaching"
---

## Teaching Areas

- Quantitative methods
- Psychometrics and measurement
- Causal inference and program evaluation
- Research synthesis and meta-analysis

## Harvard Graduate School of Education

- Adjunct Lecturer - 2026-present
- Multilevel and Longitudinal Models (S043) - 2026

## Harvard Graduate School of Education Teaching Fellowships

- Statistical and Psychometric Methods for Educational Measurement (S061) - 2024
- Research Synthesis and Meta-Analysis (S032) - 2022, 2024, 2026
- Multilevel and Longitudinal Models (S043) - 2023
- The Practice of Learning Design (LDIT PCE) - 2023
- Statistical Methods for Applied Educational Research (S052) - 2022, 2023
- Applied Linear Regression (S030) - 2018, 2019
- Designing for Learning by Creating (T550) - 2017, 2018

## New England Conservatory of Music

- Faculty, Music-in-Education (MIE) Department - 2018-2023
- Faculty, School of Continuing Education - 2019-2022
- Chair, Music-in-Education Department - 2021-2022

### Courses

- Music, Brain Development, and Learning (MIE 526)
- Music-in-Education Seminar (MIE 511)
- Introduction to Research Methods for Music Education (MIE 541)
- Introduction to Music-in-Education (MIE 501)
- Guided Internship Coordinator (MIE INT)

## Mentoring and Advising

- Faculty Instructor and Graduate Research Advisor, Boston Conservatory at Berklee (2022-present)
- Thesis Writing and Editing (M-PR 6755)
- Thesis Revisions and Defense (M-PR 6756)
- Statistical methods consulting and advising in applied educational and medical research settings
